// Studio — every product in the catalogue, in 3D: paint it, theme it, set the scene, dream it, share it.
//
// Data only: museum/catalog/products.json (generated by tools/build_catalog.mjs), museum/skins,
// museum/themes/films.json, museum/wyld_room.json, museum/events/*.json. Engine modules are shared
// with the museum: engine/skins.js (the one livery system), engine/card.js, engine/profile.js,
// engine/share.js, ui/settings.js. State lives in the URL (?p=&s=&scene=&event=) so every look is a link.
import * as THREE from 'three';
import { fitPerspectiveBounds } from '../engine/framing.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { MeshoptDecoder } from 'three/examples/jsm/libs/meshopt_decoder.module.js';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { slotsOf, applySkin, skinProblems, skinFromFilm, skinFromWyld } from '../engine/skins.js';
import { renderCard, bikeCard } from '../engine/card.js';
import { createProfile, renderSettings, QUALITY, AVATARS } from '../engine/profile.js';
import { ensureProgression } from '../engine/progression.js';
import { productAccess } from '../engine/access.js';
import { currentUser, isAdminUser } from '../cloud/supabase-lite.js';
import { captureView, shareImage } from '../engine/share.js';
import { initSettings } from '../ui/settings.js';
import { SCENES, encodeLook, decodeLook, productsFor } from './model.js';
import { createRaceSetupStore, encodeRaceSetup, decodeRaceSetup, completedSlots, setSetupSlot, RACE_SETUP_EVENT } from './race-setup.js';
import { readStorage, writeStorage } from '../engine/storage.js';
import { syncIdentityFromSetup } from '../engine/identity.js';
import { renderRaceBadges } from '../ui/race-cards.js';

import { eventEnabled, contentVisible } from '../engine/event-visibility.js';

const $ = id => document.getElementById(id);
const CAT = {...window.__PRODUCTS,products:(window.__PRODUCTS?.products||[]).filter(contentVisible)}, FILMS = window.__FILMS?.films || [], MSKINS = window.__SKINS?.skins || [], WYLD = eventEnabled('wyld') ? window.__WYLDROOM?.variants || [] : [], EVENTS = window.__EVENTS || [];
const profile = createProfile();
let adminAccess=false,pendingLockedProduct=null;
const accessForProduct=product=>productAccess(product,{state:ensureProgression(),admin:adminAccess});
const studioAccessReady=currentUser().then(user=>{adminAccess=isAdminUser(user);return adminAccess;}).catch(()=>false);
const touch = matchMedia('(pointer: coarse)').matches || innerWidth < 760;
const RS = renderSettings(profile.get().quality, { lite: touch, dpr: devicePixelRatio });
const reduce = profile.get().motion === 'reduced' || (profile.get().motion === 'auto' && matchMedia('(prefers-reduced-motion: reduce)').matches);
const q = new URLSearchParams(location.search);
const sharedSetup = decodeRaceSetup(q.get('setup'), CAT.products);
const raceSetupStore = createRaceSetupStore();
const event = EVENTS.find(e => e.id === (q.get('event') || sharedSetup?.event_id)) || null;
let raceSetup = sharedSetup || raceSetupStore.load(CAT.products);

// ---------------------------------------------------------------- renderer, camera, stage
const canvas = $('stage');
let renderer;
try { renderer = new THREE.WebGLRenderer({ canvas, antialias: !RS.lite, powerPreference: 'high-performance' }); }
catch (e) { document.body.innerHTML = '<p style="color:#fff;padding:40px;font:16px system-ui">This browser cannot show 3D. <a style="color:#5fd8d3" href="./">Back to the museum</a></p>'; throw e; }
renderer.setPixelRatio(RS.dpr); renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.shadowMap.enabled = RS.shadows; renderer.shadowMap.type = THREE.PCFShadowMap;
const scene = new THREE.Scene();
const pmrem = new THREE.PMREMGenerator(renderer);
scene.environment = pmrem.fromScene(new RoomEnvironment(), .04).texture;
const camera = new THREE.PerspectiveCamera(32, 1, .05, 200);
camera.position.set(2.6, 1.15, 3.1);
const controls = new OrbitControls(camera, canvas);
controls.target.set(0, .55, 0); controls.enableDamping = true; controls.minDistance = 1.3; controls.maxDistance = 7; controls.maxPolarAngle = Math.PI * .52; controls.enablePan = false;
const floor = new THREE.Mesh(new THREE.CircleGeometry(40, 64), new THREE.MeshStandardMaterial({ color: '#e9e2d6', roughness: .9 }));
floor.rotation.x = -Math.PI / 2; floor.receiveShadow = true; scene.add(floor);
const turntable = new THREE.Mesh(new THREE.CylinderGeometry(1.35, 1.4, .06, 64), new THREE.MeshStandardMaterial({ color: '#f4efe7', roughness: .4 }));
turntable.position.y = .03; turntable.receiveShadow = true; scene.add(turntable);
const hemi = new THREE.HemisphereLight('#ffffff', '#bfb3a3', 1.1); scene.add(hemi);
const key = new THREE.DirectionalLight('#ffffff', 2.2); key.position.set(3, 5, 2.5); key.castShadow = true; key.shadow.mapSize.set(RS.lite ? 1024 : 2048, RS.lite ? 1024 : 2048);
Object.assign(key.shadow.camera, { left: -2, right: 2, top: 2, bottom: -2, near: .5, far: 12 }); scene.add(key);
const rim = new THREE.DirectionalLight('#9fd8ff', 1.2); rim.position.set(-3, 2.2, -2.5); scene.add(rim);
const holder = new THREE.Group(); holder.position.y = .06; scene.add(holder);
const loader = new GLTFLoader(); loader.setMeshoptDecoder(MeshoptDecoder);

function sceneTex(top, bottom) {
  const c = document.createElement('canvas'); c.width = 16; c.height = 512; const g = c.getContext('2d');
  const gr = g.createLinearGradient(0, 0, 0, 512); gr.addColorStop(0, top); gr.addColorStop(1, bottom); g.fillStyle = gr; g.fillRect(0, 0, 16, 512);
  const t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; return t;
}
let sceneId = 'studio';
function setScene(id, film) {
  const s = SCENES[id] || SCENES.studio; sceneId = id;
  const top = film ? film.stops[0] : s.sky[0], bottom = film ? film.stops[2] : s.sky[1];
  document.body.style.setProperty('--studio-backdrop',top);
  scene.background?.dispose?.();
  scene.background = sceneTex(top, bottom);
  floor.material.color.set(film ? film.stops[0] : s.floor);
  hemi.intensity = s.hemi; key.intensity = s.key; key.color.set(s.keyColor); rim.color.set(film ? film.stops[4] : s.rim); rim.intensity = s.rimI;
  renderer.toneMappingExposure = s.exposure;
  scene.fog = new THREE.Fog(film ? film.stops[0] : s.sky[1], 9, 30);
  document.body.classList.toggle('light-scene', !!s.light && !film);
}

// ---------------------------------------------------------------- products, looks, loading
const cache = new Map();
let current = null, look = null, loadToken = 0, loadingProduct = false, loadedSelection = null;
const loadModel = url => {
  if (!cache.has(url)) cache.set(url, loader.loadAsync(url).then(g => g.scene).catch(error=>{cache.delete(url);throw error;}));
  const pending=cache.get(url);cache.delete(url);cache.set(url,pending);return pending;
};
function trimModelCache(){
  for(const [url,pending] of cache){
    if(cache.size<=3)break;
    if(url===current?.product.glb)continue;
    cache.delete(url);
    pending.then(model=>model.traverse(o=>{o.geometry?.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material])){m?.map?.dispose();m?.dispose();}})).catch(()=>{});
  }
}
async function show(product, lookIn) {
  const token = ++loadToken; loadingProduct = true; loadedSelection = null;
  const gate=accessForProduct(product);
  if(!gate.unlocked){
    pendingLockedProduct=product;
    current?.root?.traverse(o=>{for(const m of (Array.isArray(o.material)?o.material:[o.material]))m?.dispose?.();});
    holder.clear();current=null;loadingProduct=false;$('loading').hidden=true;
    $('heroEyebrow').textContent='LOCKED · LEVEL '+gate.requiredLevel;
    $('heroTitle').textContent=product.name;
    $('heroSub').textContent='You can inspect the facts now. The 3D bike unlocks as you explore KONA.';
    drawPanel();
    return false;
  }
  pendingLockedProduct=null; $('loading').hidden = false;
  $('heroEyebrow').textContent = [product.year || product.years || product.era, product.brand].filter(Boolean).join(' · ');
  $('heroTitle').textContent = product.name; $('heroSub').textContent = product.origin === 'studio-design' ? 'Studio design · only in the studio' : product.museum ? 'Also in the museum' : '';
  try {
    const proto = await loadModel(product.glb); if (token !== loadToken) return false;
    const bike = proto.clone(true);
    bike.traverse(o => { if (o.isMesh) { o.material = Array.isArray(o.material) ? o.material.map(m => m.clone()) : o.material.clone(); o.castShadow = true; o.receiveShadow = true; if (o.userData?.optional_accessory) o.visible = false; } });
    const b = new THREE.Box3().setFromObject(bike), c = b.getCenter(new THREE.Vector3()), size = b.getSize(new THREE.Vector3());
    const turned = size.z > size.x;                                  // some pipelines export the bike along z
    const wrap = new THREE.Group(); wrap.add(bike); bike.position.set(-c.x, -b.min.y, -c.z); if (turned) wrap.rotation.y = Math.PI / 2;
    // Cloned materials are per view; geometries/textures remain owned by the bounded model cache.
    current?.root?.traverse(o=>{for(const m of (Array.isArray(o.material)?o.material:[o.material]))m?.dispose?.();});
    holder.clear(); holder.add(wrap);
    current = { product, root: wrap, paint: slotsOf(wrap) };
    applyLook(lookIn || defaultLook(product));
    $('favBtn').setAttribute('aria-pressed', profile.get().favourites.includes(product.id)); $('favBtn').textContent = profile.get().favourites.includes(product.id) ? '♥' : '♡';
    drawPanel();resize();trimModelCache();
    loadedSelection = product.id;
    return true;
  } catch (e) {
    if (token !== loadToken) return false;
    console.warn('studio load', product.id, e);
    toast(navigator.onLine === false ? 'You are offline: this bike has not been cached yet' : 'Could not load this bike · check your connection');
    return false;
  } finally { if (token === loadToken) { loadingProduct = false; $('loading').hidden = true; } }
}
const defaultLook = p => ({ skin: p.skins?.[0] || null, finish: 'gloss', custom: null });
function skinFor(l) {
  const base = l.custom ? { ...(l.skin || {}), ...l.custom, id: 'custom', name: 'Custom', kind: 'studio' } : (l.skin || { id: 'stock', name: 'Stock' });
  const fin = { gloss: { roughness: .22, metalness: .15, clearcoat: 1 }, satin: { roughness: .42, metalness: .1, clearcoat: .4 }, matte: { roughness: .72, metalness: .05, clearcoat: 0 } }[l.finish || 'gloss'];
  return { ...base, finish: { ...fin, ...(base.finish && l.finish === 'gloss' ? base.finish : {}) } };
}
function applyLook(l) {
  if(current&&!contentVisible(l?.skin))l=defaultLook(current.product);
  look = l; if (!current) return;
  const sk = skinFor(l);
  if (sk.frame || sk.dye) applySkin(current.paint, sk);
  const film = l.theme ? FILMS.find(f => f.id === l.theme) : null;
  setScene(film ? 'film' : sceneId, film);
  writeUrl();
}
function writeUrl() {
  if (!current) return;
  const u = new URL(location.href); u.searchParams.set('p', current.product.id);
  const enc = encodeLook(look); if (enc) u.searchParams.set('s', enc); else u.searchParams.delete('s');
  u.searchParams.set('scene', sceneId); if (event) u.searchParams.set('event', event.id);
  history.replaceState(null, '', u);
}

// ---------------------------------------------------------------- panel
let tab = 'bikes', filter = { brand: null, origin: null, q: '' };
const ORIGIN = { 'canyon-model': 'Canyon, current', 'canyon-archive': 'Canyon, archive', 'geometry-study': 'Champions', 'photo-rebuild': 'Named machines', 'type-study': 'Type studies', 'studio-design': 'Studio designs' };
const h = (tag, attrs = {}, ...kids) => { const n = document.createElement(tag); for (const [k, v] of Object.entries(attrs)) { if (k.startsWith('on')) n.addEventListener(k.slice(2), v); else if (v === true) n.setAttribute(k, ''); else if (v != null && v !== false) n.setAttribute(k, v); } for (const k of kids.flat()) if (k != null) n.append(k.nodeType ? k : document.createTextNode(k)); return n; };
function drawPanel() {
  const P = $('panel'); P.replaceChildren(); P.classList.toggle('setup-mode', tab === 'setup'); $('card').hidden = tab !== 'info';
  document.querySelectorAll('.tabs [data-tab]').forEach(b => b.setAttribute('aria-selected', b.dataset.tab === tab));
  requestAnimationFrame(() => document.querySelector(`.tabs [data-tab="${tab}"]`)?.scrollIntoView({ block:'nearest', inline:'center', behavior:'auto' }));
  if (tab === 'bikes') {
    const list = productsFor(CAT.products, { ...filter, event, favourites: profile.get().favourites });
    P.append(h('input', { class: 'search', type: 'search', placeholder: `Search ${CAT.products.length} bikes`, value: filter.q, oninput: e => { filter.q = e.target.value; drawPanel(); P.querySelector('.search').focus(); } }));
    const chip = (label, on, fn) => h('button', { type: 'button', 'aria-pressed': String(on), onclick: fn }, label);
    P.append(h('div', { class: 'filters' },
      chip('All', !filter.brand && !filter.origin && !filter.fav, () => { filter = { ...filter, brand: null, origin: null, fav: false }; drawPanel(); }),
      chip('♥ Saved', !!filter.fav, () => { filter.fav = !filter.fav; drawPanel(); }),
      Object.entries(ORIGIN).map(([k, v]) => chip(v, filter.origin === k, () => { filter.origin = filter.origin === k ? null : k; drawPanel(); }))));
    P.append(h('p', { class: 'count' }, `${list.length} of ${CAT.products.length} · ${CAT.studio_only} only in the studio`));
    P.append(h('div', { class: 'grid' }, list.map(p => {
      const sw = p.skins?.[0]?.frame || '#8e979d',gate=accessForProduct(p);
      return h('button', { type: 'button', class: 'prod'+(gate.unlocked?'':' locked'), 'aria-current': String(current?.product === p), disabled:!gate.unlocked, 'aria-label':gate.unlocked?p.name:p.name+' · unlocks at Level '+gate.requiredLevel, onclick: gate.unlocked ? async () => { if (await show(p)) saveCurrentToSetup({stay:true,announce:true}); if (innerWidth < 900) dock(true); } : null },
        h('i', { class: 'sw', style: `background:${sw}` }), h('small', {}, [p.year || p.years || p.era, p.brand].filter(Boolean).join(' · ')), h('b', {}, p.name),
        !gate.unlocked ? h('span',{class:'tag'},'LEVEL '+gate.requiredLevel) : p.origin === 'studio-design' ? h('span', { class: 'tag' }, 'Studio only') : event?.featured?.includes(p.id) ? h('span', { class: 'tag' }, event.name) : null);
    })));
  } else if (tab === 'paint' && current) {
    const p = current.product, skins = p.skins || [];
    const dot = s => h('i', { style: `background:linear-gradient(135deg,${s.frame || '#888'} 58%,${s.accent || s.frame || '#888'} 58%)` });
    if (skins.length) P.append(h('div', { class: 'sec' }, h('h4', {}, 'Liveries for this bike'), h('div', { class: 'chips' }, skins.map(s =>
      h('button', { type: 'button', 'aria-pressed': String(look?.skin === s && !look?.custom && !look?.theme), onclick: () => { applyLook({ skin: s, finish: look.finish }); drawPanel(); } }, dot(s), s.name, h('small', {}, s.kind))))));
    const mine = (profile.get().liveries || []).filter(contentVisible);
    if (mine.length) P.append(h('div', { class: 'sec' }, h('h4', {}, 'My liveries'), h('div', { class: 'chips' }, mine.map(s =>
      h('button', { type: 'button', onclick: () => { applyLook({ skin: s, finish: look.finish }); drawPanel(); } }, dot(s), s.name)))));
    const base = skinFor(look);
    const slot = (k, label) => h('label', { class: 'slot' }, h('input', { type: 'color', value: base[k] || '#888888', 'aria-label': label, oninput: e => applyLook({ ...look, theme: null, custom: { ...(look.custom || {}), frame: base.frame, [k]: e.target.value } }) }), label);
    P.append(h('div', { class: 'sec' }, h('h4', {}, 'Mix your own'), h('div', { class: 'slots' },
      Object.keys(current.paint.slots).includes('frame') ? slot('frame', 'Frame') : null,
      current.paint.slots.accent ? slot('accent', 'Accent') : null, current.paint.slots.rim ? slot('rim', 'Rims') : null,
      current.paint.slots.disc ? slot('disc', 'Disc') : null, current.paint.slots.tape ? slot('tape', 'Bar tape') : null, current.paint.slots.saddle ? slot('saddle', 'Saddle') : null)));
    P.append(h('div', { class: 'sec' }, h('h4', {}, 'Finish'), h('div', { class: 'seg' }, ['gloss', 'satin', 'matte'].map(f =>
      h('button', { type: 'button', 'aria-pressed': String((look.finish || 'gloss') === f), onclick: () => { applyLook({ ...look, finish: f }); drawPanel(); } }, f[0].toUpperCase() + f.slice(1))))));
    P.append(h('div', { class: 'row' },
      h('button', { type: 'button', class: 'btn primary', onclick: saveLivery }, 'Save to my liveries'),
      h('button', { type: 'button', class: 'btn ghost', onclick: saveCurrentToSetup }, 'Add to My Kona Setup'),
      h('button', { type: 'button', class: 'btn ghost', onclick: () => { applyLook(defaultLook(p)); drawPanel(); } }, 'Reset')));
  } else if (tab === 'themes' && current) {
    const ids = event?.themes?.length ? [...event.themes, ...FILMS.map(f => f.id).filter(i => !event.themes.includes(i))] : FILMS.map(f => f.id);
    P.append(h('div', { class: 'sec' }, h('h4', {}, 'Films · the Bike Porn series'), h('div', { class: 'chips' }, ids.map(id => FILMS.find(f => f.id === id)).filter(Boolean).map(f =>
      h('button', { type: 'button', 'aria-pressed': String(look?.theme === f.id), onclick: () => { applyLook({ skin: skinFromFilm(f), finish: 'gloss', theme: f.id }); dreamCard(f); drawPanel(); } },
        h('i', { style: `background:conic-gradient(${f.stops.join(',')})` }), f.film, h('small', {}, f.persona))))));
    P.append(h('div', { class: 'sec' }, h('h4', {}, 'Museum looks'), h('div', { class: 'chips' },
      [...WYLD.map(skinFromWyld), ...MSKINS.filter(s => s.kind === 'theme')].map(s => h('button', { type: 'button', onclick: () => { applyLook({ skin: s, finish: 'gloss' }); drawPanel(); } },
        h('i', { style: `background:${s.dye ? 'conic-gradient(#ff3d8e,#e9cde8,#5fd8d3,#ff3d8e)' : s.frame}` }), s.name)))));
  } else if (tab === 'scene') {
    P.append(h('div', { class: 'sec' }, h('h4', {}, 'Scene'), h('div', { class: 'chips' }, Object.entries(SCENES).filter(([k]) => k !== 'film').map(([k, s]) =>
      h('button', { type: 'button', 'aria-pressed': String(sceneId === k), onclick: () => { setScene(k); writeUrl(); drawPanel(); } }, h('i', { style: `background:linear-gradient(${s.sky[0]},${s.sky[1]})` }), s.label)))));
    P.append(h('div', { class: 'sec' }, h('h4', {}, 'Quality'), h('p', { class: 'count' }, `${QUALITY[profile.get().quality].label} · change it in your profile`),
      h('button', { type: 'button', class: 'btn ghost', onclick: () => settingsUI.open() }, 'Profile and quality')));
  } else if (tab === 'setup') {
    renderRaceSetup(P);
  } else if (tab === 'info' && current) {
    const p = current.product;
    renderCard({ ...bikeCard({ name: p.name, year: p.year, era: p.era || p.years, maker: p.brand, kind: p.origin === 'type-study' || p.origin === 'studio-design' ? 'type' : 'named', text: p.text || '', geometry: {}, skins: p.skins || [], facts: (p.facts || []).map(f => [f.cls, f.text]), ref: p.ref, arch: p.family }, { method: p.atlasKey ? window.__ATLAS_METHOD : null }), stats: [],
      actions: [p.where?.[0] ? { label: `See it: ${p.where[0].name}`, primary: true, href: `./?room=${encodeURIComponent(p.where[0].id)}` } : null, p.deepStudio ? { label: 'Engineering studio', href: p.deepStudio } : null].filter(Boolean) });
    $('card').hidden = false;
    if (p.where?.length) P.append(h('p', { class: 'src' }, 'In the museum: ', p.where.map((w, i) => [i ? ' · ' : '', h('a', { href: `./?room=${encodeURIComponent(w.id)}` }, w.name)])));
    else P.append(h('p', { class: 'src' }, 'Only in the studio.'));
    P.append(h('p', { class: 'src' }, 'Sources: ', (p.sources || []).map((s, i) => [i ? ' · ' : '', s.url ? h('a', { href: s.url, target: '_blank', rel: 'noopener' }, s.label) : `${s.label} (${s.file})`])));
  }
}
function setupShareUrl() {
  const enc = encodeRaceSetup(raceSetup, CAT.products); if (!enc) return location.href;
  const u = new URL(location.href);
  for (const k of ['p','s','scene','event']) u.searchParams.delete(k);
  u.searchParams.set('setup', enc);
  return u.href;
}
function saveCurrentToSetup({stay=false,announce=false}={}) {
  if (!current || loadingProduct) { toast('Wait for your bike to finish loading'); return; }
  if (loadedSelection !== current.product.id) { toast('Choose a bike that loaded successfully before saving'); return; }
  const previousSetup = readStorage('raceSetup');
  raceSetup = setSetupSlot(raceSetup, 'bike', current.product, { look:encodeLook(look), scene:sceneId }, CAT.products);
  try { raceSetup = raceSetupStore.save(raceSetup, CAT.products); }
  catch (error) { toast(error.message); return; }
  const saved = syncIdentityFromSetup(raceSetup, CAT.products);
  if(saved.persisted === false){writeStorage('raceSetup',previousSetup);toast('Your setup could not be saved. Previous progress was kept.');return;}
  toast(announce ? 'Bike selected for your Race Self' : 'Saved to My Kona Setup');
  if (!stay) { tab = 'setup'; dock(false); drawPanel(); }
}
async function shareRaceSetup() {
  if (!raceSetup?.slots?.bike) { toast('Add a bike to your setup first'); return; }
  const product = CAT.products.find(p => p.id === raceSetup.slots.bike.product_id);
  if (!product) return;
  const blob = await captureView(renderer, scene, camera, { title: 'My Kona 2026 Setup', place: product.name, site: 'KONA' });
  const r = await shareImage(blob, {
    title: 'My Kona 2026 Setup',
    text: `My Kona 2026 Setup · ${product.name}`,
    url: setupShareUrl(),
    filename: `kona-setup-${product.id}.jpg`
  });
  toast({ shared:'Shared', link:'Link shared', saved:'Image saved', cancelled:'Not shared' }[r]);
}
function renderRaceSetup(P) {
  const raceBadges=document.createElement('div'); raceBadges.className='studio-race-badges';
  renderRaceBadges(raceBadges,{limit:8,empty:false});
  const bikeProduct = raceSetup?.slots?.bike ? CAT.products.find(p => p.id === raceSetup.slots.bike.product_id) : null;
  const n = completedSlots(raceSetup);
  const slot = (icon, label, value, state, onclick, soon=false) => h('button', {
    type:'button', class:`setup-slot${soon ? ' soon' : ''}`, disabled: soon, onclick
  }, h('i', {}, icon), h('span', {}, h('b', {}, label), h('small', {}, value)), h('span', { class:'status' }, state));
  P.append(
    h('div', { class:'setup-scroll' },
      h('div', { class:'setup-head' },
        h('div', {}, h('small', {}, 'Kona 2026'), h('h3', {}, 'My Kona Setup')),
        h('div', { class:'setup-score' }, `${n} / 4`)
      ),
      h('div', { class:'setup-grid' },
        slot('△', 'Bike', bikeProduct ? `${bikeProduct.brand} · ${bikeProduct.name}` : 'Choose your race bike', bikeProduct ? '✓' : '○', () => { tab='bikes'; drawPanel(); }),
        slot('◉', 'Wheels', bikeProduct ? 'Current bike wheels' : 'Comes with your bike', bikeProduct ? '✓' : '○', () => { tab='bikes'; drawPanel(); }),
        slot('◒', 'Helmet', 'Equipment slot ready', 'Soon', null, true),
        slot('⌁', 'Shoes', 'Alphafly 3 study', 'Museum', () => { location.href = 'index.html?room=nike-running'; })
      ),
      h('p', { class:'setup-note' }, 'Stored only on this device. The shoe opens the Nike Running Lab, an independent study in the museum. The helmet slot stays closed until a validated asset clears intake.'),
      raceBadges
    ),
    h('div', { class:'setup-actions' },
      h('button', { type:'button', class:'btn primary', onclick:saveCurrentToSetup }, bikeProduct && current?.product.id === bikeProduct.id ? 'Update bike' : 'Save bike'),
      bikeProduct ? h('button', { type:'button', class:'btn ghost', 'aria-label':'Share My Kona Setup', onclick:shareRaceSetup }, 'Share setup') : null
    )
  );
}
function saveLivery() {
  const s = { ...skinFor(look), id: `mine-${Date.now().toString(36)}`, name: `${current.product.name.split(' ').slice(-1)[0]} ${((profile.get().liveries || []).length + 1)}`, kind: 'studio' };
  delete s.dye;
  if (skinProblems(s).length) { toast('That livery could not be saved'); return; }
  profile.set({ liveries: [s, ...(profile.get().liveries || [])].slice(0, 40) });
  toast('Saved to your liveries'); drawPanel();
}

// ---------------------------------------------------------------- dream mode: the bike in motion
let dreaming = false, dreamT = 0;
function dreamCard(f) {
  $('dreamEyebrow').textContent = f ? `${f.persona} · ${f.place}` : [current?.product.brand, current?.product.year].filter(Boolean).join(' · ');
  $('dreamName').textContent = f ? f.name : current?.product.name || '';
  $('dreamLine').textContent = f ? `“${f.tagline}”` : (event?.share_line || '');
  $('dreamTitle').classList.remove('on'); void $('dreamTitle').offsetWidth; $('dreamTitle').classList.add('on');
}
function setDream(on) {
  dreaming = on; document.body.classList.toggle('dreaming', on); $('dreamBtn').setAttribute('aria-pressed', on);
  controls.enabled = !on; dreamT = 0;
  if (on) dreamCard(look?.theme ? FILMS.find(f => f.id === look.theme) : null);
}

// ---------------------------------------------------------------- chrome: tabs, dock, share, favourites, settings
function dock(min) { $('dock').classList.toggle('min', min); document.body.classList.toggle('dock-min', min); }
document.querySelectorAll('.tabs [data-tab]').forEach(b => b.addEventListener('click', () => { tab = b.dataset.tab; dock(false); drawPanel(); }));
$('dockBtn').onclick = () => dock(!$('dock').classList.contains('min'));
$('dreamBtn').onclick = () => setDream(!dreaming);
$('favBtn').onclick = () => { if (!current) return; profile.toggleFavourite(current.product.id); const on = profile.get().favourites.includes(current.product.id); $('favBtn').setAttribute('aria-pressed', on); $('favBtn').textContent = on ? '♥' : '♡'; toast(on ? 'Saved to your favourites' : 'Removed from favourites'); };
let toastT; function toast(m) { const t = $('toast'); t.textContent = m; t.classList.add('on'); clearTimeout(toastT); toastT = setTimeout(() => t.classList.remove('on'), 2400); }
$('shareBtn').onclick = async () => {
  if (!current) return;
  const film = look?.theme ? FILMS.find(f => f.id === look.theme) : null;
  const title = `${current.product.name}${film ? ` · ${film.name}` : look?.custom ? ' · my livery' : ''}`;
  const blob = await captureView(renderer, scene, camera, { title, place: event ? `${event.name} · Studio` : 'Studio', site: 'KONA' });
  const r = await shareImage(blob, { title, text: event?.share_line ? `${event.share_line}: ${title}` : `${title} · built in KONA Bike Studio`, url: location.href, filename: `studio-${current.product.id}.jpg` });
  toast({ shared: 'Shared', link: 'Link shared', saved: 'Image saved', cancelled: 'Not shared' }[r]);
};
const settingsUI = initSettings({ profile, QUALITY, AVATARS, activeQuality: () => profile.get().quality,
  onQuality: id => { const n = renderSettings(id, { lite: touch, dpr: devicePixelRatio }); renderer.setPixelRatio(n.dpr); resize(); renderer.shadowMap.enabled = n.shadows; return n.lite !== RS.lite; },
  onSound: () => false, onMotion: () => true, sync: { available: false } });
if (event) { $('eventPill').hidden = false; $('eventPill').textContent = `${event.name} · ${event.place.split(',')[0]}`; $('eventPill').style.borderColor = event.accent; }

// ---------------------------------------------------------------- loop
function resize() {
  const w=Math.max(1,canvas.clientWidth),hh=Math.max(1,canvas.clientHeight);
  renderer.setSize(w,hh,false);camera.aspect=w/hh;camera.fov=38;camera.updateProjectionMatrix();
  if(current){
    const bounds=new THREE.Box3().setFromObject(current.root);
    fitPerspectiveBounds(camera,controls,bounds,{direction:[.65,.2,1],padding:1.15});
  }
}
const stageResize=new ResizeObserver(resize);stageResize.observe(canvas);resize();
let last = performance.now();
renderer.setAnimationLoop(now => {
  if(document.hidden||document.body.classList.contains('settings-open')){last=now;return;}
  const dt = Math.min(.05, (now - last) / 1000); last = now;
  if (dreaming && !reduce) {                                          // a slow crane around the bike
    dreamT += dt; const a = dreamT * .22, r = 3.2 + Math.sin(dreamT * .17) * .6;
    camera.position.set(Math.cos(a) * r, .45 + Math.sin(dreamT * .13) * .35 + .5, Math.sin(a) * r); camera.lookAt(0, .55, 0);
    holder.rotation.y = 0;
  } else { controls.update(); if (!reduce && !controls.state?.active) holder.rotation.y += dt * .08; }
  renderer.render(scene, camera);
});

// ---------------------------------------------------------------- start: from the link, the event, or the first product
const requestedScene = sharedSetup?.slots?.bike?.configuration?.scene || q.get('scene');
setScene(requestedScene && SCENES[requestedScene] ? requestedScene : (event ? 'kona' : 'studio'));
const start = CAT.products.find(p => p.id === (sharedSetup?.slots?.bike?.product_id || q.get('p'))) || (event && CAT.products.find(p => p.id === event.featured?.[0])) || CAT.products[0];
const fromLink = decodeLook(sharedSetup?.slots?.bike?.configuration?.look || q.get('s'), start, FILMS);
if (sharedSetup?.slots?.bike) tab = 'setup';
studioAccessReady.then(()=>{
  const initial=q.has('p')||sharedSetup?.slots?.bike ? start : CAT.products.find(p=>accessForProduct(p).unlocked)||start;
  return show(initial, initial===start?fromLink:null);
});
dock(false);
window.__studio = { CAT, show, applyLook, setDream, get current() { return current; }, get look() { return look; }, get raceSetup() { return raceSetup; }, saveCurrentToSetup, renderer, scene, camera };
