import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULT_AIR as E,STOCK,density,forces,solveSpeed,compare,parseCurve,interpolate,signature} from '../src/aero.mjs';
const model={base:.23,deltas:{rearDisc:-.004}},near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
test('standard dry air; humidity lowers density',()=>{near(density(15,1013.25,0),1.225,0.0001);assert.ok(density(15,1013.25,100)<density(15,1013.25,0));});
test('independent force balance and cubic still-air aero power',()=>{const e={...E,humidity:0},r=forces(e,model,STOCK),v=40/3.6,rho=density(15,1013.25,0);near(r.aero,.5*rho*.23*v**3);near(r.power,(r.aero+.0035*84.1*9.80665*v)/.975);near(forces({...e,speed:80},model,STOCK).aero/r.aero,8);});
test('crosswind uses apparent speed and axial coefficient without double projection',()=>{const r=forces({...E,crosswind:10},model,STOCK);near(r.yaw,Math.atan(10/40)*180/Math.PI);near(r.drag,.5*r.rho*((40/3.6)**2+(10/3.6)**2)*.23);assert.equal(forces({...E,crosswind:40},model,STOCK),null);});
test('solver residual under headwind, tailwind, crosswind and grade',()=>{for(const headwind of [-10,0,15])for(const crosswind of [0,7])for(const grade of [0,3]){const e={...E,headwind,crosswind,grade},v=solveSpeed(e,model,STOCK);assert.ok(v>0);near(forces(e,model,STOCK,v).power,250,1e-7);}});
test('signed gains and losses; identical setups give zero',()=>{let c=compare(E,model,model,STOCK,STOCK);near(c.wattsSaved,0);near(c.timeSaved,0);c=compare(E,model,model,{...STOCK,rearDisc:true},STOCK);assert.ok(c.wattsSaved>0&&c.timeSaved>0);c=compare(E,{...model,base:.26},model,STOCK,STOCK);assert.ok(c.wattsSaved<0&&c.timeSaved<0);});
test('curve import validates numbers, duplicates, bounds and interpolation; no extrapolation',()=>{const c=parseCurve('yaw_deg,cda_m2\n-10,0.24\n0,0.23\n10,0.25');near(interpolate(c,5),.24);assert.equal(interpolate(c,11),null);for(const s of ['yaw_deg,cda_m2\n0,.2\n0,.3','yaw_deg,cda_m2\n0,\n1,.3','yaw_deg,cda_m2\n0,NaN\n1,.3','yaw_deg,cda_m2\n0,.2\n50,.3'])assert.throws(()=>parseCurve(s));});
test('import binds to configuration; accessory changes invalidate, paint does not',()=>{const m={curve:[[-20,.2],[20,.24]],signature:signature(STOCK)};assert.ok(forces(E,m,{...STOCK,frame:'#f00'}));assert.equal(forces(E,m,{...STOCK,rearDisc:true}),null);});
// rider system removed; bike-only CdA model
