// The museum registry: every area, named, with the bikes and works in it. Generated from data:
// museum/world/rooms.json, museum/world/wings/*.json, museum/catalog/products.json, museum/art/*.json.
// Writes docs/ROOMS.md (the human map). Run after tools/build_catalog.mjs.
import {contentVisible} from '../web/src/engine/event-visibility.js';
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const J = f => JSON.parse(fs.readFileSync(path.join(root, f), 'utf8'));
const rooms = {...J('museum/world/rooms.json'),areas:J('museum/world/rooms.json').areas.filter(contentVisible)}, cat = J('museum/catalog/products.json').products;
const wings = J('museum/world/wings/index.json').wings.map(f => J(`museum/world/wings/${f}`));
const paint = Object.fromEntries(J('museum/art/paintings.json').paintings.map(p => [p.id, p])), sculpt = Object.fromEntries(J('museum/art/sculptures.json').sculptures.map(s => [s.id, s]));
const at = id => cat.filter(p => p.where.some(w => w.id === id));
const line = p => `${p.name}${p.sub ? ` — ${p.sub}` : ''} · ${[p.year || p.years, p.brand].filter(Boolean).join(', ')} (\`${p.id}\`)`;
let md = `# Rooms and what is in them\n\nGenerated by \`node tools/build_registry.mjs\` from \`museum/world/rooms.json\`, the wing files and the catalogue. Do not edit by hand.\n\n`;
const totals = { areas: 0, bikes: 0, works: 0 };
for (const fl of rooms.floors) {
  md += `## ${fl.name}\n\n`;
  for (const a of rooms.areas.filter(a => a.floor === fl.id)) {
    const bikes = at(a.id); totals.areas++; totals.bikes += bikes.length;
    md += `### ${a.name}${a.hidden ? ' *(hidden)*' : ''}\n*${a.sub}* · map id \`${a.id}\`\n\n`;
    md += bikes.length ? bikes.map(p => `- ${line(p)}`).join('\n') + '\n' : a.exhibits?.remembered ? '' : '- no bikes\n';
    if (a.exhibits?.remembered) md += `- plus ${a.exhibits.remembered} generations remembered without a model\n`;
    md += '\n';
  }
  for (const w of wings.filter(w => w.floor === fl.id)) {
    totals.areas++;
    md += `### ${w.name} (wing)\n*${w.sub}* · map id \`wing-${w.id}\`\n\n`;
    for (const r of w.rooms) {
      totals.areas++;
      const id = `atlas-${w.id}-${r.id}`, bikes = at(id), works = [...(r.paintings || []).map(x => `painting: ${paint[x]?.title}`), ...(r.sculptures || []).map(x => `sculpture: ${sculpt[x]?.title}`)];
      totals.bikes += bikes.length; totals.works += works.length;
      md += `#### ${r.name}\n*${r.sub}* · map id \`${id}\`${r.feature ? ` · ${r.feature}` : ''}\n\n`;
      md += [...bikes.map(p => `- ${line(p)}`), ...works.map(x => `- ${x}`)].join('\n') || '- (see feature)';
      md += '\n\n';
    }
  }
}
const studioOnly = cat.filter(p => !p.museum);
md += `## Only in the studio\n\n${studioOnly.map(p => `- ${line(p)}`).join('\n')}\n\n`;
md += `## Totals\n\n| | |\n|---|---|\n| Areas | ${totals.areas} |\n| Bikes placed in the museum | ${totals.bikes} (some models appear in more than one room) |\n| Paintings and sculptures | ${totals.works} |\n| Products in the studio | ${cat.length} (${studioOnly.length} studio-only) |\n`;
fs.writeFileSync(path.join(root, 'docs/ROOMS.md'), md);
console.log(`ROOMS.md · ${totals.areas} areas · ${totals.bikes} bike placements · ${totals.works} works · ${cat.length} studio products`);
