#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const cfg=read('museum/game/progression-v2.json');
const relics=read('museum/game/relics-v2.json');
const unlocks=read('museum/game/unlocks-v2.json');
const finds=read('museum/game/finds-v1.json');
const out='// GENERATED by tools/build_game_config.mjs. Edit museum/game/*.json, never this file.\n'+
  'export const PROGRESSION_CONFIG=Object.freeze('+JSON.stringify(cfg)+');\n'+
  'export const RELIC_REGISTRY=Object.freeze('+JSON.stringify(relics)+');\n'+
  'export const UNLOCK_REGISTRY=Object.freeze('+JSON.stringify(unlocks)+');\n'+
  'export const FIND_REGISTRY=Object.freeze('+JSON.stringify(finds)+');\n';
const target=path.join(root,'web/src/generated/game-config.js');
if(process.argv.includes('--check')){
  if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==out){console.error('generated game config is stale');process.exit(1);}
  console.log('game config current');process.exit(0);
}
fs.mkdirSync(path.dirname(target),{recursive:true});
fs.writeFileSync(target,out);
console.log('generated game config');
