import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const sha = execFileSync('git',['rev-parse','--short=8','HEAD'],{encoding:'utf8'}).trim();
const branch = execFileSync('git',['rev-parse','--abbrev-ref','HEAD'],{encoding:'utf8'}).trim();
const out = `# KONA Repository Status

This file is generated by \`node tools/write-status.mjs\`.

- branch: \`${branch}\`
- commit: \`${sha}\`
- product: KONA
- proposition: Race the version of yourself
- privacy: local-first; account optional
- 3D: loaded after explicit Explore intent

## Canonical docs

- README.md
- docs/PRODUCT.md
- docs/ARCHITECTURE.md
- docs/DATA_MODEL.md
- docs/DESIGN_SYSTEM.md
- docs/SECURITY_PRIVACY.md
- docs/OPERATIONS.md
- docs/ROADMAP.md
- docs/DECISIONS.md

Do not treat dated audits or archived handovers as current production truth.
`;
fs.writeFileSync('STATUS.generated.md',out);
console.log(`status written for ${sha}`);
