import * as THREE from 'three';
export function collectTriangles(root,scale=0.2){
 if(!Number.isFinite(scale)||scale<=0||scale>1)throw Error('Scale must be >0 and ≤1.');
 root.updateWorldMatrix(true,true);const values=[],m=new THREE.Matrix4(),world=new THREE.Matrix4(),v=new THREE.Vector3();
 const walk=o=>{if(o!==root&&(!o.visible||/decal|graphic/i.test(o.name+' '+(o.userData?.part||''))))return;
 if(o.isMesh){const g=o.geometry,p=g.attributes.position,idx=g.index,n=idx?idx.count:p.count;
  for(let instance=0;instance<(o.isInstancedMesh?o.count:1);instance++){world.copy(o.matrixWorld);if(o.isInstancedMesh){o.getMatrixAt(instance,m);world.multiply(m);}const flip=world.determinant()<0;
   for(let j=0;j+2<n;j+=3)for(const k of flip?[0,2,1]:[0,1,2]){v.fromBufferAttribute(p,idx?idx.getX(j+k):j+k).applyMatrix4(world);values.push(v.x*1000*scale,-v.z*1000*scale,v.y*1000*scale);}
  }}for(const c of o.children)walk(c);
 };walk(root);if(!values.length)throw Error('No visible printable geometry in this part.');
 const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<values.length;i++){if(!Number.isFinite(values[i]))throw Error('Non-finite geometry rejected.');const k=i%3;min[k]=Math.min(min[k],values[i]);max[k]=Math.max(max[k],values[i]);}
 const origin=[(min[0]+max[0])/2,(min[1]+max[1])/2,min[2]];for(let i=0;i<values.length;i++)values[i]-=origin[i%3];return {triangles:values,dimensions:max.map((x,i)=>x-min[i]),scale};
}
export function encodeSTL(values){if(values.length%9)throw Error('Triangle data must have nine coordinates per face.');const buf=new ArrayBuffer(84+values.length/9*50),view=new DataView(buf);new Uint8Array(buf).set(new TextEncoder().encode('Speedmax display replica; units mm; inspect report before slicing'));view.setUint32(80,values.length/9,true);const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3(),n=new THREE.Vector3();for(let i=0,o=84;i<values.length;i+=9,o+=50){a.fromArray(values,i);b.fromArray(values,i+3);c.fromArray(values,i+6);n.copy(b).sub(a).cross(c.sub(a)).normalize();[...n.toArray(),...values.slice(i,i+9)].forEach((v,k)=>{if(!Number.isFinite(v))throw Error('Non-finite STL rejected');view.setFloat32(o+k*4,v,true);});}return new Uint8Array(buf);}
export function topology(values){const edges=new Map();let degenerate=0;const keys=new Map();let next=0;const vertex=(i)=>{const key=values.slice(i,i+3).map(x=>Math.round(x*1000)).join(',');if(!keys.has(key))keys.set(key,next++);return keys.get(key);};for(let i=0;i<values.length;i+=9){const a=vertex(i),b=vertex(i+3),c=vertex(i+6);const u=[values[i+3]-values[i],values[i+4]-values[i+1],values[i+5]-values[i+2]],v=[values[i+6]-values[i],values[i+7]-values[i+1],values[i+8]-values[i+2]];if(new Set([a,b,c]).size<3||Math.hypot(u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0])<1e-10){degenerate++;continue;}for(const [x,y] of [[a,b],[b,c],[c,a]]){const key=x<y?x+','+y:y+','+x,entry=edges.get(key)||[0,0];entry[0]++;entry[1]+=x<y?1:-1;edges.set(key,entry);}}
 let boundary=0,nonManifold=0,winding=0;for(const [n,dir] of edges.values()){if(n===1)boundary++;else if(n!==2)nonManifold++;else if(dir!==0)winding++;}return {triangles:values.length/9,weldToleranceMm:.001,boundaryEdges:boundary,nonManifoldEdges:nonManifold,inconsistentEdges:winding,degenerateFaces:degenerate,closedEdgeTopology:!boundary&&!nonManifold&&!winding&&!degenerate,limits:'Edge topology only. Intersecting shells, wall thickness, support, strength and tolerances are not validated. Display replicas only.'};}
const table=Array.from({length:256},(_,n)=>{let c=n;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
export function zipStore(files){let offset=0;const chunks=[],central=[];const u16=(v,o,n)=>v.setUint16(o,n,true),u32=(v,o,n)=>v.setUint32(o,n>>>0,true);for(const [name,raw] of files){const bytes=typeof raw==='string'?new TextEncoder().encode(raw):raw,label=new TextEncoder().encode(name);let crc=0xffffffff;for(const b of bytes)crc=table[(crc^b)&255]^(crc>>>8);crc=(crc^0xffffffff)>>>0;
 const h=new Uint8Array(30+label.length),v=new DataView(h.buffer);u32(v,0,0x04034b50);u16(v,4,20);u16(v,6,0x800);u32(v,14,crc);u32(v,18,bytes.length);u32(v,22,bytes.length);u16(v,26,label.length);h.set(label,30);chunks.push(h,bytes);
 const c=new Uint8Array(46+label.length),w=new DataView(c.buffer);u32(w,0,0x02014b50);u16(w,4,20);u16(w,6,20);u16(w,8,0x800);u32(w,16,crc);u32(w,20,bytes.length);u32(w,24,bytes.length);u16(w,28,label.length);u32(w,42,offset);c.set(label,46);central.push(c);offset+=h.length+bytes.length;}
 const size=central.reduce((s,c)=>s+c.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);u32(v,0,0x06054b50);u16(v,8,files.length);u16(v,10,files.length);u32(v,12,size);u32(v,16,offset);const out=new Uint8Array(offset+size+22);let at=0;for(const chunk of [...chunks,...central,end]){out.set(chunk,at);at+=chunk.length;}return out;}
