export function makeSpecs({profile,parts}){
 const s=profile.bike?.specs;if(!s)return;const panel=document.getElementById('geometry');panel.querySelector('h2').textContent='Dimensions & specification';panel.querySelector('.lead').textContent='Published Canyon data, the model’s size-M anchors, and every listed component. Choose a section below.';
 const section=document.createElement('section');section.id='full-specs';const header=document.createElement('div');header.className='spec-summary';header.innerHTML=`<b>${s.name}</b><span>${s.weightKg} kg · size ${s.size} · MY${s.year}</span><strong>${new Intl.NumberFormat('sv-SE',{maximumFractionDigits:0}).format(s.priceSEK)} SEK</strong><small>Complete bike · Canyon listing checked ${s.checkedAt.slice(0,10)}</small>`;section.append(header);
 const source=document.createElement('a');source.href=s.source;source.target='_blank';source.rel='noopener';source.textContent='Open official Canyon specification ↗';source.className='spec-source';section.append(source);
 const groups=new Map();for(const c of s.components){if(!groups.has(c.group))groups.set(c.group,[]);groups.get(c.group).push(c);}for(const [group,items] of groups){const d=document.createElement('details');d.className='spec-group';d.open=group===groups.keys().next().value;const summary=document.createElement('summary');summary.textContent=group+' · '+items.length;d.append(summary);for(const item of items){const card=document.createElement('article');card.className='spec-card';const small=document.createElement('small');small.textContent=item.type;const title=document.createElement('b');title.textContent=item.name;card.append(small,title);const dl=document.createElement('dl');for(const [key,value] of Object.entries(item.features)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;dl.append(dt,dd);}card.append(dl);d.append(card);}section.append(d);}
 const audit=document.createElement('div');audit.className='spec-audit';const front=parts.wheel_front.position,rear=parts.wheel_rear.position,bb=parts.crankset.position;const checks=[['Wheelbase',s.geometryBySize.M['Wheel Base'].value,1000*(front.x-rear.x)],['Chainstay',s.geometryBySize.M['Chainstay Length'].value,1000*bb.distanceTo(rear)],['BB drop',s.geometryBySize.M['Bottom Bracket Offset'].value,1000*(rear.y-bb.y)]];audit.innerHTML='<h3>Model versus Canyon · size M</h3><p class="lab-small">Distances between assembled model pivots, in millimetres. These checks do not validate hidden surface shapes.</p><table><thead><tr><th>Dimension</th><th>Canyon</th><th>Model</th></tr></thead><tbody>'+checks.map(([k,a,b])=>`<tr><td>${k}</td><td>${a}</td><td>${b.toFixed(2)}</td></tr>`).join('')+'</tbody></table>';section.append(audit);
 if(s.discrepancies.length){const d=document.createElement('details');d.className='spec-group';const title=document.createElement('summary');title.textContent='Source discrepancies';d.append(title);for(const note of s.discrepancies){const p=document.createElement('p');p.className='lab-small';p.textContent=note;d.append(p);}section.append(d);}
 panel.querySelector('#geo').before(section);const geometry=document.createElement('details');geometry.className='spec-group';const title=document.createElement('summary');title.textContent='Geometry · all published sizes';geometry.append(title,panel.querySelector('#geo'));section.before(geometry);
}
