import {collectTriangles,encodeSTL,topology,zipStore} from './print.mjs';
import prices from '../../museum/prices-se.json';
export function makeWorkshop({parts,PARTS,explodables,scene,download,select,getCfg,profile={}}){
 const panel=document.getElementById('parts'),box=document.createElement('section');box.className='workshop';box.innerHTML=`<div class="fit-tabs"><button class="active" data-work-tab="catalog">Components</button><button data-work-tab="print">3D print</button></div><section data-work-page="catalog"><p class="lab-small">Sweden · SEK · checked ${prices.checkedAt.slice(0,10)}<br>VAT included; shipping excluded. Offline quotes; verify current variants at Canyon.</p><input id="parts-search" class="work-search" placeholder="Find a component…" aria-label="Search components"><div id="price-list"></div></section><section data-work-page="print" hidden><h3>Your scale model</h3><p class="lab-small">Export the current fitted geometry in millimetres, centred and placed on the build plate. Paint and flat decals do not become printable relief.</p><label class="lab-field">Part or assembly<select id="print-part"></select></label><label class="lab-field">Scale<select id="print-scale"><option value="0.2">1:5 · display model</option><option value="0.1">1:10 · miniature</option><option value="0.5">1:2 · study</option><option value="1">1:1 · full size</option></select></label><div class="actions"><button id="print-check">Inspect mesh</button><button id="print-one" class="primary">STL + report</button></div><button id="print-all" class="lab-action">Export all parts · ZIP</button><p id="print-status" class="lab-small" role="status">Visual replicas, not functional cycling components. Fine features, intersections and thickness need slicer review. Parent assemblies overlap with their child exports.</p></section>`;
 panel.querySelector('#bom').before(box);panel.querySelector('#bom').hidden=true;panel.querySelector('.lead').textContent='Inspect, price and export the components of your build.';if(profile.partsReplace){panel.querySelector('.lead').textContent='Inspect and export the components of this archived build.';const n=box.querySelector('[data-work-page=catalog] .lab-small');if(n)n.textContent='From the archived Canyon specification. These parts are no longer sold.';}const $=id=>document.getElementById(id),ids=Object.keys(PARTS).filter(k=>!PARTS[k].alias&&parts[k]);
 box.querySelectorAll('[data-work-tab]').forEach(b=>b.onclick=()=>{box.querySelectorAll('[data-work-tab]').forEach(x=>x.classList.toggle('active',x===b));box.querySelectorAll('[data-work-page]').forEach(x=>x.hidden=x.dataset.workPage!==b.dataset.workTab);});
 const money=n=>new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0}).format(n);
 function list(){const q=$('parts-search').value.toLowerCase();$('price-list').replaceChildren();for(const id of ids.filter(k=>(k+' '+PARTS[k].name+' '+PARTS[k].group+' '+PARTS[k].spec).toLowerCase().includes(q))){const p=PARTS[id],quote=(!profile.compatiblePriceParts||profile.compatiblePriceParts.includes(id))?prices.items[id]:null,row=document.createElement('article');row.className='price-card';const btn=document.createElement('button');btn.textContent=p.name;btn.onclick=()=>select(id);row.append(btn);const detail=document.createElement('p');detail.className='lab-small';detail.textContent=profile.partsReplace?(p.spec||'Archived component'):quote?`${money(quote.price)} · ${quote.match==='exact'?'Exact listing':'Product family'} · ${quote.availability==='InStock'?'Listed in stock':'Listed out of stock'}`:'No matching standalone Canyon quote found';row.append(detail);if(quote){const note=document.createElement('small');note.textContent=quote.note;row.append(note);const link=document.createElement('a');link.href=quote.url;link.textContent='View Canyon listing ↗';link.target='_blank';link.rel='noopener';row.append(link);}const print=document.createElement('button');print.className='part-print';print.textContent='Print this part →';print.onclick=()=>{$('print-part').value=id;box.querySelector('[data-work-tab=print]').click();};row.append(print);$('price-list').append(row);}
 const upgrade=profile.partsReplace?null:prices.items.aeroshield_pro_upgrade;if(!q&&upgrade){const el=document.createElement('p');el.className='lab-small';el.textContent=`Optional upgrade: ${upgrade.name} · ${money(upgrade.price)} · ${upgrade.availability}. This is not the price of the stock AeroShield.`;const a=document.createElement('a');a.href=upgrade.url;a.textContent=' View upgrade ↗';a.target='_blank';a.rel='noopener';el.append(a);$('price-list').append(el);}}
 $('parts-search').oninput=list;list();for(const id of ids){const o=document.createElement('option');o.value=id;o.textContent=PARTS[id].name;$('print-part').append(o);}
 function capture(id){const saved=explodables.map(x=>x.node.position.clone());try{explodables.forEach(x=>x.node.position.copy(x.base));scene.updateMatrixWorld(true);const data=collectTriangles(parts[id],+$('print-scale').value),check=topology(data.triangles);return {bytes:encodeSTL(data.triangles),report:{part:id,name:PARTS[id].name,units:'mm',scale:data.scale,dimensionsMm:data.dimensions,...check,configuration:getCfg()}};}finally{explodables.forEach((x,i)=>x.node.position.copy(saved[i]));scene.updateMatrixWorld(true);}}
 const status=r=>`${r.name} · ${r.dimensionsMm.map(x=>x.toFixed(1)).join(' × ')} mm · ${r.triangles.toLocaleString()} triangles. ${r.closedEdgeTopology?'Closed edge topology.':'Review: '+r.boundaryEdges+' boundary edges, '+r.nonManifoldEdges+' non-manifold edges, '+r.degenerateFaces+' degenerate faces.'} Slicer / wall-thickness review still required.`;
 $('print-check').onclick=()=>{try{$('print-status').textContent=status(capture($('print-part').value).report);}catch(e){$('print-status').textContent=e.message;}};
 $('print-one').onclick=()=>{try{const id=$('print-part').value,r=capture(id);download(new Blob([zipStore([[id+'.stl',r.bytes],['print-report.json',JSON.stringify(r.report,null,2)]])],{type:'application/zip'}),`Speedmax_${id}_print.zip`);$('print-status').textContent=status(r.report);}catch(e){$('print-status').textContent=e.message;}};
 $('print-all').onclick=async()=>{const button=$('print-all');button.disabled=true;const files=[],reports=[];try{for(let i=0;i<ids.length;i++){const id=ids[i];$('print-status').textContent=`Preparing ${i+1}/${ids.length} · ${PARTS[id].name}`;await new Promise(r=>setTimeout(r,0));try{const r=capture(id);files.push([id+'.stl',r.bytes]);reports.push(r.report);}catch(e){reports.push({part:id,error:e.message});}}files.push(['print-report.json',JSON.stringify(reports,null,2)]);download(new Blob([zipStore(files)],{type:'application/zip'}),'Speedmax_All_Parts_Print.zip');$('print-status').textContent=`Exported ${files.length-1} STL files plus individual reports. Check topology and printability in your slicer.`;}finally{button.disabled=false;}};
 return {capture,prices,ids};
}
