import puppeteer from 'puppeteer-core';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'output/playwright'),downloads=path.join(out,'downloads');fs.mkdirSync(downloads,{recursive:true});
const browser=await puppeteer.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=metal','--enable-gpu','--ignore-gpu-blocklist']});const report=[];
try{for(const [name,width,height] of [['desktop',1512,982],['mobile',390,844]]){
 const p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.setViewport({width,height,deviceScaleFactor:1,isMobile:name==='mobile',hasTouch:name==='mobile'});
 const client=await p.createCDPSession();await client.send('Page.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
 await p.goto(new URL('../Speedmax_Museum.html',import.meta.url).href);await p.waitForFunction(()=>window.__sm?.lab&&document.body.classList.contains('ready'));await p.waitForFunction(()=>+getComputedStyle(document.querySelector('#loader')).opacity<.01);
 await p.locator('#labOpen').click();await p.waitForFunction(()=>window.__sm.rider.enabled);await new Promise(r=>setTimeout(r,1500));
 assert.equal(await p.evaluate(()=>window.__sm.lab.result.wattsSaved),0);assert.deepEqual(await p.evaluate(()=>[...document.querySelectorAll('input[type=number]')].filter(e=>!e.checkValidity()).map(e=>e.id)),[]);
 await p.locator('[data-lab-config="rearDisc"]').click();assert.equal(await p.evaluate(()=>window.__sm.discMesh.visible&&!window.__sm.parts.spokes_rear.visible),true);assert.ok(await p.evaluate(()=>window.__sm.lab.result.wattsSaved>3));
 const input=async(id,val)=>p.$eval(id,(e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},String(val));
 await input('#lab-crosswind',8);assert.ok(await p.evaluate(()=>window.__sm.lab.result.now.yaw>10));
 await p.$eval('#lab',e=>e.scrollTop=0);await new Promise(r=>setTimeout(r,200));await p.screenshot({path:path.join(out,`aero-lab-${name}.png`)});
 await p.locator('#riderOpen').click();await p.locator('[data-fit-tab=body]').click();await input('#fit-inseam',84);await p.locator('#fit-starter').click();await p.locator('[data-fit-tab=analysis]').click();await p.locator('#fit-search').click();assert.equal(await p.$eval('#fit-apply',e=>e.hidden),false);await p.locator('#fit-apply').click();assert.ok(await p.evaluate(()=>window.__sm.S.cfg.riderDelta<0));
 await p.locator('#rider-panel .x').click();await p.locator('#labOpen').click();await p.$eval('#lab',e=>e.scrollTop=0);await p.locator('#lab-pin').click();assert.equal(await p.evaluate(()=>window.__sm.lab.result.wattsSaved),0);
 const csv=path.join(out,'test-curve.csv');fs.writeFileSync(csv,'yaw_deg,cda_m2\n-20,0.24\n0,0.23\n20,0.24\n');await p.$eval('#lab-csv',e=>e.closest('details').open=true);await p.$eval('#lab-source',e=>e.value='Synthetic automated-test fixture, not measured');await (await p.$('#lab-csv')).uploadFile(csv);await p.waitForFunction(()=>!!window.__sm.lab.state.model.curve);assert.ok(await p.evaluate(()=>!!window.__sm.lab.result.now));
 await p.locator('[data-lab-config="rearDisc"]').click();assert.equal(await p.evaluate(()=>window.__sm.lab.result.now),null);assert.match(await p.$eval('#lab-status',e=>e.textContent),/SETUP CHANGED/);
 await p.$eval('#lab-assumptions',e=>e.open=true);await p.locator('#lab-use-assumptions').click();await input('#lab-crosswind',30);await input('#lab-speed',20);assert.equal(await p.evaluate(()=>window.__sm.lab.result.now),null);await input('#lab-crosswind',0);await input('#lab-speed',40);
 await p.locator('#lab-exit').click();await p.locator('[data-drawer="build"]').click();
 const png=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,512,256);g.addColorStop(0,'#f71676');g.addColorStop(.5,'#aa1bed');g.addColorStop(1,'#05e8d2');x.fillStyle=g;x.fillRect(0,0,512,256);x.fillStyle='#ffe15d';for(let i=-256;i<700;i+=100){x.beginPath();x.moveTo(i,0);x.lineTo(i+35,0);x.lineTo(i+291,256);x.lineTo(i+256,256);x.fill();}return c.toDataURL().split(',')[1];});
 const file=path.join(out,'paint-test.png');fs.writeFileSync(file,Buffer.from(png,'base64'));await (await p.$('#paintFile')).uploadFile(file);await p.waitForFunction(()=>window.__sm.paint.enabled);await input('#paint-scale',1.4);await input('#paint-opacity',.9);await p.locator('#paint-repeat').click();
 await p.$eval('#build',e=>e.scrollTop=0);await new Promise(r=>setTimeout(r,1600));await p.screenshot({path:path.join(out,`paint-studio-${name}.png`)});
 if(name==='desktop'){const dest=path.join(downloads,'Speedmax_Your_Paint.html');if(fs.existsSync(dest))fs.unlinkSync(dest);await p.locator('#paint-save').click();for(let i=0;i<60&&!fs.existsSync(dest);i++)await new Promise(r=>setTimeout(r,100));assert.ok(fs.existsSync(dest));const saved=await browser.newPage();saved.on('pageerror',e=>errors.push(e.message));await saved.goto('file://'+dest);await saved.waitForFunction(()=>window.__sm?.paint?.enabled);assert.equal(await saved.$eval('#paint-scale',e=>e.value),'1.4');await saved.close();}
 await p.locator('#paint-remove').click();assert.equal(await p.evaluate(()=>window.__sm.paint.enabled),false);
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);report.push({name,disc:true,crosswind:true,riderFit:true,positionSearch:true,curveImport:true,staleCurveRejected:true,unsupportedYawRejected:true,artworkUpload:true,artworkRemoval:true,paintedHtmlReopen:name==='desktop',errors});await p.close();
}fs.writeFileSync(path.join(root,'assets/museum/lab-browser-checks.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}finally{await browser.close();}
